[workspace]
authors = ["JoerivanEngelen <joerivanengelen@hotmail.com>"]
channels = ["conda-forge"]
name = "fdf-docs"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
render = "quarto render"
preview = "quarto preview"

[dependencies]
quarto = ">=1.7.32,<2"
