services:
  migrate:
    image: ${HARBOR_REGISTRY}/fair-data/${PROJECT_NAME}:${IMAGE_TAG}
    container_name: migrate
    restart: "no"
    env_file:
      - ./.env
    command: bash -c "pypgstac migrate && alembic upgrade head"

  backend:
    image: ${HARBOR_REGISTRY}/fair-data/${PROJECT_NAME}:${IMAGE_TAG}
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

